//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMS_Authontication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AfterSale
    {
        public long Id { get; set; }
        public string CompanyName { get; set; }
        public string BranchName { get; set; }
        public string VisitReason { get; set; }
        public string PersonName { get; set; }
        public Nullable<System.DateTime> VisitDate { get; set; }
        public string Region { get; set; }
        public string Phone { get; set; }
        public Nullable<bool> HasFeedBack { get; set; }
        public string FeedBackText { get; set; }
        public string Note { get; set; }
        public Nullable<System.DateTime> FeedBackDate { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
        public string DeletedBy { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<bool> IsNew { get; set; }
        public string MeetingTime { get; set; }
        public string StartMeeting { get; set; }
        public string EndMeeting { get; set; }
    } 
}
