//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMS_Authontication1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class AnalysisLossRatio
    {
        public long Code { get; set; }
        
        [Display(Name = "Company ID :")]
        public Nullable<long> CompId { get; set; }
        [Display(Name = "Contract No :")]
        public Nullable<int> ContractNo { get; set; }
        [Display(Name = "Loss Ratio :")]
        public Nullable<double> LossRatio { get; set; }
        [Display(Name = "Pool Value :")]
        public Nullable<double> PoolPercent { get; set; }
        [Display(Name = "Company ID :")]
        public Nullable<double> PoolValue { get; set; }
        [Display(Name = "Pool State :")]
        public bool PoolState { get; set; }
        [Display(Name = "Company ID :")]
        public string FileName { get; set; }
        [Display(Name = "Service Date :")]
        public Nullable<System.DateTime> ServiceDate { get; set; }
        [Display(Name = "Created Date :")]
        public Nullable<System.DateTime> ClaimCreatedDate { get; set; }
        [Display(Name = "Review Date :")]
        public Nullable<System.DateTime> ReviewDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string UpdatedBy { get; set; }       
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<bool> Active { get; set; }

    }
}
