//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMS_Authontication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApprovalDetail
    {
        public int Id { get; set; }
        public string FilePath { get; set; }
        public Nullable<int> ApprovalId { get; set; }
        public Nullable<long> EnumRequestId { get; set; }
    
        public virtual ApprovalMaster ApprovalMaster { get; set; }
        public virtual Enum_Requests Enum_Requests { get; set; }
    }
}
