//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMS_Authontication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApprovalBil
    {
        public int Id { get; set; }
        public string Code { get; set; }
        public Nullable<System.DateTime> EnterDate { get; set; }
        public Nullable<System.DateTime> ExitDate { get; set; }
        public Nullable<double> TotalValue { get; set; }
        public Nullable<int> ProviderCode { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    }
}
