//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMS_Authontication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Basic_Data
    {
        public int Id { get; set; }
        public int BS_CODE { get; set; }
        public string SOURCE_MOD { get; set; }
        public int COMP_ID { get; set; }
        public int BRANCH_CODE { get; set; }
        public string BS_CODE_UP { get; set; }
        public string BS_ANAME { get; set; }
        public string BS_ENAME { get; set; }
        public string BS_TYPE { get; set; }
        public string NOTES { get; set; }
        public string ACTIVE { get; set; }
        public string SERV_CODE { get; set; }
        public string PHONE { get; set; }
        public string EMAIL { get; set; }
        public Nullable<int> AMT { get; set; }
        public Nullable<System.DateTime> START_DATE { get; set; }
        public Nullable<System.DateTime> END_DATE { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
        public string CREATED_BY { get; set; }
        public string UPDATE_BY { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public Nullable<int> ISSUE_QTY { get; set; }
        public Nullable<int> DELV_QTY { get; set; }
        public string ADJUST_TYP { get; set; }
        public Nullable<int> ADJUST_PERIOD { get; set; }
        public Nullable<int> MAX_COLLECT_TIME { get; set; }
        public string USED_TYP { get; set; }
        public Nullable<int> USED_VAL { get; set; }
        public Nullable<int> USED_PERIOD { get; set; }
        public Nullable<int> NO_RETURN_MONTH { get; set; }
        public string USED_TYP_ADD { get; set; }
        public Nullable<bool> IsSync { get; set; }
        public Nullable<System.DateTime> SyncDate { get; set; }
        public string SyncBy { get; set; }
    }
}
