//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMS_Authontication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Broker
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Broker()
        {
            this.ProposalMains = new HashSet<ProposalMain>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string NationalId { get; set; }
        public long MembershipNo { get; set; }
        public long TaxCardId { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public bool IsCompany { get; set; }
        public string TaxCardName { get; set; }
        public string PracticeCardName { get; set; }
        public string CompanyName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProposalMain> ProposalMains { get; set; }
    }
}
