//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMS_Authontication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CardAcceptionReason
    {
        public int id { get; set; }
        public int AcceptionId { get; set; }
        public int AcceptionReasonsId { get; set; }
        public Nullable<bool> IsSync { get; set; }
        public Nullable<System.DateTime> SyncDate { get; set; }
        public string SyncBy { get; set; }
        public Nullable<double> PatientPercent { get; set; }
        public Nullable<double> PatientAmount { get; set; }
    
        public virtual AcceptionReason AcceptionReason { get; set; }
    }
}
