//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMS_Authontication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Claim
    {
        public int Id { get; set; }
        public Nullable<double> Policy_No { get; set; }
        public string Group_Name { get; set; }
        public Nullable<System.DateTime> Effective_Date { get; set; }
        public Nullable<System.DateTime> Expiry_Date { get; set; }
        public string Unique_Member_ID { get; set; }
        public Nullable<int> ClassCode { get; set; }
        public string Member_Name { get; set; }
        public string Member_Country { get; set; }
        public string Member_Gender { get; set; }
        public string Relation { get; set; }
        public Nullable<int> DOB { get; set; }
        public Nullable<int> Age { get; set; }
        public string Coverage { get; set; }
        public string Sub_Coverage { get; set; }
        public string Med_Cond_Description { get; set; }
        public Nullable<long> Claim_ID { get; set; }
        public string Claim_Source { get; set; }
        public string Claim_Country_Of_Treatment { get; set; }
        public Nullable<System.DateTime> Claim_Date { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public Nullable<double> Claim_Amount { get; set; }
        public Nullable<double> Claim_Approved_Amount { get; set; }
        public Nullable<double> Claim_Net_Amount { get; set; }
        public string Claim_Currency { get; set; }
        public Nullable<int> Provider_Code { get; set; }
        public string Provider_Name { get; set; }
        public string ProviderType { get; set; }
        public string TreatmentType { get; set; }
        public string Transaction_Type { get; set; }
        public string CC { get; set; }
        public string Department { get; set; }
        public string Network { get; set; }
        public Nullable<System.DateTime> Month { get; set; }
        public string Coverage2 { get; set; }
        public string InOut_P { get; set; }
        public string Sub_Coverage_Type { get; set; }
        public string Expected__NET { get; set; }
    }
}
