//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMS_Authontication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Co_Insurance_01
    {
        public int id { get; set; }
        public Nullable<double> CO_ID { get; set; }
        public string LIVEL { get; set; }
        public Nullable<double> INSURANCE_DAY { get; set; }
        public Nullable<double> INSURANCE_MONTH { get; set; }
        public Nullable<double> LAB_DAY { get; set; }
        public Nullable<double> RAY_DAY { get; set; }
        public Nullable<double> INSURANCE_DAY_LAB { get; set; }
        public Nullable<double> INSURANCE_MONTH_LAB { get; set; }
        public Nullable<double> COST_MONTHLY_YEAR { get; set; }
        public Nullable<double> COST_DALLY_YEAR { get; set; }
        public Nullable<double> NO_CLAEM_WEEK { get; set; }
        public Nullable<double> NO_CLEEM_YEAR { get; set; }
        public Nullable<double> FREE { get; set; }
        public Nullable<double> NO_CLM_DAY_YYYY { get; set; }
        public Nullable<double> MONY_CLM_DAY_YYYY { get; set; }
        public Nullable<double> NO_CLM_MON_YYYY { get; set; }
        public Nullable<double> MONY_CLM_MON_YYYY { get; set; }
        public Nullable<double> MED_DAY { get; set; }
        public Nullable<double> MED_MONTH { get; set; }
        public Nullable<bool> IsSync { get; set; }
        public Nullable<System.DateTime> SyncDate { get; set; }
        public string SyncBy { get; set; }
    }
}
