//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMS_Authontication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyContractPhoto
    {
        public int Id { get; set; }
        public Nullable<int> ContractNo { get; set; }
        public Nullable<int> CompId { get; set; }
        public string EName { get; set; }
        public string AName { get; set; }
        public string ContractLong { get; set; }
        public string Contractype { get; set; }
        public string Path1 { get; set; }
        public string Path2 { get; set; }
        public string Path3 { get; set; }
        public string Path4 { get; set; }
        public string Path5 { get; set; }
        public string Path6 { get; set; }
        public string Path7 { get; set; }
        public string Path8 { get; set; }
        public string Path9 { get; set; }
        public string Path10 { get; set; }
        public string Path11 { get; set; }
        public string Path12 { get; set; }
        public string Path13 { get; set; }
        public string Path14 { get; set; }
        public string Path15 { get; set; }
        public string Path16 { get; set; }
        public string Path17 { get; set; }
        public string Path18 { get; set; }
        public string Path19 { get; set; }
        public string Path20 { get; set; }
        public Nullable<System.DateTime> ContractDate { get; set; }
        public string DeleteFlag { get; set; }
    }
}
