//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMS_Authontication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMP_CUSTOMIZED_D_D_MED_EMP
    {
        public long Id { get; set; }
        public int COMP_ID { get; set; }
        public int BRANCH_CODE { get; set; }
        public int C_COMP_ID { get; set; }
        public int CONTRACT_NO { get; set; }
        public string SERV_CODE { get; set; }
        public string D_SERV_CODE { get; set; }
        public string CLASS_CODE { get; set; }
        public string SER_SERV { get; set; }
        public string CARD_ID { get; set; }
        public Nullable<double> DAY_AMT { get; set; }
        public Nullable<double> DAY_NO { get; set; }
        public Nullable<double> MON_AMT { get; set; }
        public Nullable<double> MON_NO { get; set; }
        public Nullable<double> LAB_NO { get; set; }
        public Nullable<double> RAY_NO { get; set; }
        public Nullable<double> LAB_NO_MON { get; set; }
        public Nullable<double> RAY_NO_MON { get; set; }
        public Nullable<double> DAY_MED_AMT_MON { get; set; }
        public Nullable<double> DAY_NO_ROSHTA_MON { get; set; }
        public Nullable<double> MON_MED_AMT_MON { get; set; }
        public Nullable<double> MON_NO_ROSHTA_MON { get; set; }
        public Nullable<double> DAY_MED_AMT_YEAR { get; set; }
        public Nullable<double> DAY_NO_ROSHTA_YEAR { get; set; }
        public Nullable<double> MON_MED_AMT_YEAR { get; set; }
        public Nullable<double> MON_NO_ROSHTA_YEAR { get; set; }
        public string ACTIVE { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
        public string UPDATE_BY { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public Nullable<int> VISIT_NO { get; set; }
        public Nullable<int> VISIT_NO_MON { get; set; }
        public Nullable<int> SESSION_NO { get; set; }
        public Nullable<int> SESSION_NO_MON { get; set; }
        public Nullable<bool> IsSync { get; set; }
        public Nullable<System.DateTime> SyncDate { get; set; }
        public string SyncBy { get; set; }
    }
}
