//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMS_Authontication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompStatement
    {
        public int Id { get; set; }
        public Nullable<int> CompID { get; set; }
        public Nullable<int> MainCompCode { get; set; }
        public string CompSpecification { get; set; }
        public string FlagIndependent { get; set; }
        public Nullable<int> ContractNo { get; set; }
        public string Insured { get; set; }
        public string FormerClient { get; set; }
        public Nullable<int> OldCompId { get; set; }
        public string CompNameOther { get; set; }
        public Nullable<System.DateTime> DatePrint { get; set; }
    }
}
