//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMS_Authontication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompContractClassEmp
    {
        public int Id { get; set; }
        public Nullable<int> COMP_ID { get; set; }
        public Nullable<int> BRANCH_CODE { get; set; }
        public Nullable<int> C_COMP_ID { get; set; }
        public Nullable<int> CONTRACT_NO { get; set; }
        public string CLASS_CODE { get; set; }
        public string CARD_ID { get; set; }
        public Nullable<int> EMP_CODE { get; set; }
        public Nullable<int> AREA_CODE { get; set; }
        public string FILE_IMG { get; set; }
        public Nullable<double> MAX_AMOUNT { get; set; }
        public Nullable<double> ANNUAL_PREM { get; set; }
        public Nullable<int> HOSPITAL_DEGREE { get; set; }
        public Nullable<int> COVER_RELATION { get; set; }
        public Nullable<double> OVER_AGE_COND { get; set; }
        public Nullable<double> OVER_AGE_PERT { get; set; }
        public Nullable<double> OVER_AGE_AMT { get; set; }
        public Nullable<double> AMBULANCE { get; set; }
        public Nullable<double> AMBULANCE_AMT { get; set; }
        public Nullable<int> NO_EMPLOYEES { get; set; }
        public Nullable<double> MAX_CEILING { get; set; }
        public string CRIT_CASE { get; set; }
        public Nullable<int> CRIT_CASE_DAYS { get; set; }
        public Nullable<int> CRIT_CASE_AMT { get; set; }
        public Nullable<double> PERT_CEILING { get; set; }
        public Nullable<double> COVER_RELATION_AMT { get; set; }
        public Nullable<int> SON_OVER_COVER_DATE { get; set; }
        public Nullable<int> CARD_FEE_FRST { get; set; }
        public Nullable<int> CARD_FEE_OTH { get; set; }
        public Nullable<int> CASH_CARD_FLAG { get; set; }
        public Nullable<int> COVER_AGE_FROM { get; set; }
        public Nullable<int> COVER_AGE_TO { get; set; }
        public Nullable<int> SON_COVER_FROM { get; set; }
        public Nullable<int> SON_COVER_TO { get; set; }
        public Nullable<int> ALLOW_PERIOD { get; set; }
        public Nullable<int> INTEREST_TYP { get; set; }
        public Nullable<int> INTEREST_VAL { get; set; }
        public Nullable<int> DELAY_PERT { get; set; }
        public Nullable<int> STOP_INDEM { get; set; }
        public Nullable<int> STOP_APPROVAL { get; set; }
        public Nullable<int> STOP_ISSUE_CARD { get; set; }
        public Nullable<int> DELIVER_CHECKS_PERIOD { get; set; }
        public Nullable<int> P_BEF_CANCEL_CONTRACT { get; set; }
        public Nullable<int> TRAVEL_COVER_AMT { get; set; }
        public Nullable<int> TRAVEL_COVER_PERT { get; set; }
        public Nullable<System.DateTime> START_COVER { get; set; }
        public Nullable<System.DateTime> END_COVER { get; set; }
        public Nullable<int> SON_RELATION_TYP { get; set; }
        public Nullable<int> OVER_AGE_METHOD { get; set; }
        public Nullable<int> OVER_CEILING_PERT { get; set; }
        public string OVER_CEILING_PROC { get; set; }
        public string PRINT_CARD { get; set; }
        public Nullable<int> PRINTED_NUM { get; set; }
        public string NOTES { get; set; }
        public string ACTIVE { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
        public string UPDATE_BY { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public Nullable<System.DateTime> PRINT_DATE { get; set; }
        public Nullable<System.DateTime> RE_PRINT_DATE { get; set; }
        public Nullable<System.DateTime> STOP_DATE { get; set; }
        public string DLEV_CARD { get; set; }
        public Nullable<System.DateTime> DELV_DATE { get; set; }
        public Nullable<bool> IsSync { get; set; }
        public Nullable<System.DateTime> SyncDate { get; set; }
        public string SyncBy { get; set; }
    }
}
