//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMS_Authontication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comp_Customized_D_D
    {
        public int ID { get; set; }
        public Nullable<int> COMP_ID { get; set; }
        public Nullable<int> BRANCH_CODE { get; set; }
        public Nullable<int> C_COMP_ID { get; set; }
        public Nullable<int> CONTRACT_NO { get; set; }
        public string SERV_CODE { get; set; }
        public string D_SERV_CODE { get; set; }
        public string CLASS_CODE { get; set; }
        public string SER_SERV { get; set; }
        public Nullable<int> CEILING_AMT { get; set; }
        public Nullable<int> CEILING_PERT { get; set; }
        public Nullable<int> NO_DAYS { get; set; }
        public string NOTES { get; set; }
        public string ACTIVE { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
        public string UPDATE_BY { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public string SER_SERV_H { get; set; }
        public string POLL_FLAG { get; set; }
        public string SERV_DET_LEV { get; set; }
        public string REQ_APPRPV { get; set; }
        public string REQ_LETTER { get; set; }
        public string IND_LIST_PRICE { get; set; }
        public Nullable<decimal> REPEAT_NO { get; set; }
        public string REPEAT_TYP { get; set; }
        public Nullable<int> REPEAT_PERIOD { get; set; }
        public Nullable<int> CARR_AMT { get; set; }
        public string MAT_COV_TYP { get; set; }
        public string DOC_EXP { get; set; }
        public string DOC_EXP_VAL_TYP { get; set; }
        public Nullable<int> DOC_EXP_VALUE { get; set; }
        public string REFUND_FLAG { get; set; }
        public Nullable<bool> IsSync { get; set; }
        public Nullable<System.DateTime> SyncDate { get; set; }
        public string SyncBy { get; set; }
        public string POLL_CONSUMPTION { get; set; }
    }
}
