//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMS_Authontication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompContractClassProvider
    {
        public int Id { get; set; }
        public Nullable<int> COMP_ID { get; set; }
        public Nullable<int> CONTRACT_NO { get; set; }
        public string CLASS_CODE { get; set; }
        public Nullable<int> PROV_DEGREE { get; set; }
        public Nullable<int> PRV_TYP { get; set; }
        public Nullable<int> PR_CODE { get; set; }
        public Nullable<int> SERV_CODE { get; set; }
        public Nullable<int> COPAY_AMT { get; set; }
        public Nullable<int> COPAY_PERC { get; set; }
        public Nullable<int> MAX_AMOUNT { get; set; }
        public string NOTES { get; set; }
        public string ACTIVE { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
        public string UPDATE_BY { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public string TYPE { get; set; }
        public string PR_NAME { get; set; }
        public string RESIDENT_DEGREE { get; set; }
        public Nullable<bool> IsSync { get; set; }
        public Nullable<System.DateTime> SyncDate { get; set; }
        public string SyncBy { get; set; }
    }
}
