//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMS_Authontication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompIcdCpt
    {
        public int Id { get; set; }
        public Nullable<double> CLAIM_NO { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
        public Nullable<System.DateTime> CLAIM_DATE { get; set; }
        public string CARD_NO { get; set; }
        public Nullable<long> COMP_ID { get; set; }
        public string CLASS_CODE { get; set; }
        public Nullable<int> EMP_CODE { get; set; }
        public string EMP_ANAME { get; set; }
        public string TAKHASOS { get; set; }
        public Nullable<int> PRV_NO { get; set; }
        public string PRV_NAME { get; set; }
        public Nullable<double> SERV_CODE { get; set; }
        public string SERV_ANAME { get; set; }
        public Nullable<int> GROUP_NO { get; set; }
        public string GROUP_ENAME { get; set; }
        public string ICD { get; set; }
        public string CPT { get; set; }
    }
}
