//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMS_Authontication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company_Cost_Center
    {
        public int Id { get; set; }
        public Nullable<int> COMP_ID { get; set; }
        public Nullable<int> BRANCH_CODE { get; set; }
        public Nullable<int> C_COMP_ID { get; set; }
        public string COST_CODE { get; set; }
        public Nullable<int> DEPT_ID { get; set; }
        public string A_NAME { get; set; }
        public string E_NAME { get; set; }
        public string ADDRESS1 { get; set; }
        public string ADDRESS2 { get; set; }
        public string TEL1 { get; set; }
        public string TEL2 { get; set; }
        public string MOBILE { get; set; }
        public string FAX { get; set; }
        public string EMAIL { get; set; }
        public string NOTES { get; set; }
        public string ACTIVE { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
        public string UPDATE_BY { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public string CHK_NAME { get; set; }
        public Nullable<int> DOC_CODE { get; set; }
        public Nullable<int> NO_DOC_DAYS { get; set; }
        public string DEPUTY_ADDRESS { get; set; }
        public string DEPUTY_JOB { get; set; }
    }
}
