//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMS_Authontication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONSUMPTION_POOL
    {
        public int Id { get; set; }
        public Nullable<int> COMP_ID { get; set; }
        public Nullable<int> CONTRACT_NO { get; set; }
        public string CLASS_CODE { get; set; }
        public Nullable<int> COST_CODE { get; set; }
        public Nullable<int> POLL_CODE { get; set; }
        public string NAME_POOL { get; set; }
        public Nullable<int> MAX_AMOUNT { get; set; }
        public Nullable<int> AMOUNT { get; set; }
        public Nullable<int> REMAINING { get; set; }
        public string NOTES { get; set; }
        public string ACTIVE { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
        public string UPDATED_BY { get; set; }
        public Nullable<System.DateTime> UPDATED_DATE { get; set; }
        public string LAST_UPDATED_BY { get; set; }
        public Nullable<System.DateTime> LAST_UPDATED_DATE { get; set; }
        public Nullable<bool> IsSync { get; set; }
        public Nullable<System.DateTime> SyncDate { get; set; }
        public string SyncBy { get; set; }
    }
}
