//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMS_Authontication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contract_Comp
    {
        public int Id { get; set; }
        public int C_COMP_ID { get; set; }
        public Nullable<int> COMP_ID { get; set; }
        public Nullable<int> BRANCH_CODE { get; set; }
        public string C_ANAME { get; set; }
        public string C_ENAME { get; set; }
        public string ADDRESS1 { get; set; }
        public string ADDRESS2 { get; set; }
        public string TEL1 { get; set; }
        public string TEL2 { get; set; }
        public string FAX { get; set; }
        public string EMAIL { get; set; }
        public Nullable<int> DOC_CODE { get; set; }
        public Nullable<int> BROKER_CODE { get; set; }
        public Nullable<int> BROK_PERT { get; set; }
        public string PAYMENT_TYP { get; set; }
        public string ACTIVE { get; set; }
        public string NOTES { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
        public string CREATED_BY { get; set; }
        public string UPDATE_BY { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public string CANCEL_REASON { get; set; }
        public string SERIAL_TYP { get; set; }
        public string CHECK_TYP { get; set; }
        public string CHK_NAME { get; set; }
        public Nullable<int> DOC_NO_DAYS { get; set; }
        public string DEPUTY_ADDRESS { get; set; }
        public string DEPUTY_JOB { get; set; }
        public Nullable<System.DateTime> CANCEL_DATE { get; set; }
        public string BROK_PAY_TYP { get; set; }
        public string DAYS_W_M { get; set; }
        public Nullable<bool> IsSync { get; set; }
        public Nullable<System.DateTime> SyncDate { get; set; }
        public string SyncBy { get; set; }
    }
}
