//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMS_Authontication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeliveryRequest
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DeliveryRequest()
        {
            this.DeliveryRequestDetails = new HashSet<DeliveryRequestDetail>();
        }
    
        public long Id { get; set; }
        public Nullable<long> EmployeeDataId { get; set; }
        public Nullable<int> CountryId { get; set; }
        public Nullable<int> RegionId { get; set; }
        public string NeighborHood { get; set; }
        public string StreetName { get; set; }
        public Nullable<int> BuldingNo { get; set; }
        public Nullable<int> FlatNo { get; set; }
        public string Phone1 { get; set; }
        public string Phone2 { get; set; }
        public string CardId { get; set; }
        public Nullable<int> ProviderId { get; set; }
        public Nullable<long> BranchId { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public string Time { get; set; }
        public Nullable<bool> IsConfirmed { get; set; }
    
        public virtual Country Country { get; set; }
        public virtual EmployeePersonalData EmployeePersonalData { get; set; }
        public virtual Region Region { get; set; }
        public virtual SERV_PROVIDERS_NEW SERV_PROVIDERS_NEW { get; set; }
        public virtual Serv_Providers1 Serv_Providers1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DeliveryRequestDetail> DeliveryRequestDetails { get; set; }
    }
}
