//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMS_Authontication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeliveryRequestDetail
    {
        public long Id { get; set; }
        public string MedicineCode { get; set; }
        public string MedicineName { get; set; }
        public Nullable<double> Amount { get; set; }
        public string DosageForm { get; set; }
        public Nullable<long> RequestId { get; set; }
    
        public virtual DeliveryRequest DeliveryRequest { get; set; }
    }
}
