//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMS_Authontication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Diagnosi
    {
        public int Id { get; set; }
        public string DIAG_CODE { get; set; }
        public Nullable<int> SPEC_ID { get; set; }
        public Nullable<int> COMP_ID { get; set; }
        public Nullable<int> BRANCH_CODE { get; set; }
        public string DIAG_ANAME { get; set; }
        public string DIAG_ENAME { get; set; }
        public string DIAG_CODE_H { get; set; }
        public Nullable<int> COMP_ID_H { get; set; }
        public Nullable<int> BRANCH_CODE_H { get; set; }
        public Nullable<int> SERV_LEVEL { get; set; }
        public string SERV_TYP { get; set; }
        public string ACTIVE { get; set; }
        public string NOTES { get; set; }
        public string REF_FLAG { get; set; }
        public Nullable<int> OLD_DIAG_CODE { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
        public string CREATED_BY { get; set; }
        public string UPDATE_BY { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public Nullable<bool> IsSync { get; set; }
        public Nullable<System.DateTime> SyncDate { get; set; }
        public string SyncBy { get; set; }
    }
}
