//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMS_Authontication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DMSComplaint
    {
        public long Id { get; set; }
        public Nullable<int> DepartnentId { get; set; }
        public string EmployeeName { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public string Reason { get; set; }
        public string Description { get; set; }
        public string Status { get; set; }
        public string SolveProblem { get; set; }
        public Nullable<System.DateTime> ProblemDate { get; set; }
        public string PhoneNumber { get; set; }
        public string CompName { get; set; }
    
        public virtual Department Department { get; set; }
    }
}
