//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMS_Authontication1.Models
{
    using DMS_Authontication1.Migrations;
    using System;
    using System.Collections.Generic;
    
    public partial class Doctors_Permissions
    {
        public int Id { get; set; }
        public ApplicationUser User { get; set; }
        public string UserId { get; set; }
        public bool Status { get; set; }
        public string permissionType { get; set; }
        public DailyPermission DailyPermission { get; set; }
        public Nullable<int> DailyPermissionId { get; set; }
        //public IEnumerable<DailyPermission> DailyPermissions{ get; set; }

        public  MonthlyPermission MonthlyPermission { get; set; }

        public Nullable<int> MonthlyPermissionId { get; set; }



    }
}
