//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMS_Authontication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee_Request
    {
        public int REQUEST_CODE { get; set; }
        public Nullable<int> EMP_CODE { get; set; }
        public string EMP_ENAME_ST { get; set; }
        public string EMP_ENAME_SC { get; set; }
        public string EMP_ENAME_TH { get; set; }
        public string EMP_ENAME_FR { get; set; }
        public string EMP_ANAME_ST { get; set; }
        public string EMP_ANAME_SC { get; set; }
        public string EMP_ANAME_TH { get; set; }
        public string EMP_ANAME_FR { get; set; }
        public string NATIONAL_ID { get; set; }
        public Nullable<System.DateTime> BIRTHDATE { get; set; }
        public Nullable<int> GENDER { get; set; }
        public string MOBILE { get; set; }
        public string EMAIL { get; set; }
        public Nullable<System.DateTime> START_DATE { get; set; }
        public Nullable<System.DateTime> END_DATE { get; set; }
        public string EMP_RELATION { get; set; }
        public string EMP_IMG { get; set; }
        public string ADDRESS { get; set; }
        public string BRANCH { get; set; }
        public string RECEIVE_CARD { get; set; }
        public string EMP_CLASS { get; set; }
        public string EMP_CLASS_REASON { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
        public string UPDATED_BY { get; set; }
        public Nullable<System.DateTime> UPDATED_DATE { get; set; }
        public Nullable<int> TYPE { get; set; }
        public string REGISTER_TYPE { get; set; }
        public string CARD_ID { get; set; }
        public Nullable<System.DateTime> TERMINATE_DATE { get; set; }
        public string DELIVER_CARD_FLAG { get; set; }
        public Nullable<System.DateTime> DELIVER_CARD_DATE { get; set; }
        public string APPROVE_FLAG { get; set; }
        public string PRINT_REASON { get; set; }
        public string PRINT_IMG { get; set; }
        public Nullable<System.DateTime> REOPEN_DATE { get; set; }
        public string NEW_CARD_ID { get; set; }
        public string GLASSES { get; set; }
        public string DISEASE { get; set; }
        public string TYP_EMP_UPDATE { get; set; }
        public Nullable<int> COMP_ID { get; set; }
        public string FLAG_REMOVE { get; set; }
        public string CHANG_EMP_NAME { get; set; }
        public string REPRINT_EMP_CARD { get; set; }
        public string RESON { get; set; }
        public Nullable<System.DateTime> DATE_CHANGE_TYP { get; set; }
        public Nullable<int> RELATION { get; set; }
    }
}
