//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMS_Authontication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeData
    {
        public long Id { get; set; }
        public string FirstArName { get; set; }
        public string SecArName { get; set; }
        public string ThirArName { get; set; }
        public string FourArName { get; set; }
        public string FirstEnName { get; set; }
        public string SecEnName { get; set; }
        public string ThirEnName { get; set; }
        public string FourEnName { get; set; }
        public long NationalId { get; set; }
        public string Mobile1 { get; set; }
        public string Mobile2 { get; set; }
        public string Mobile3 { get; set; }
        public string Mobile4 { get; set; }
        public string HomeMobile { get; set; }
        public int CountryId { get; set; }
        public int RegionId { get; set; }
        public int GenderId { get; set; }
        public string CARD_ID { get; set; }
        public string Address { get; set; }
        public string DeliveryTime { get; set; }
        public string DeliveryStatus { get; set; }
    
        public virtual Country Country { get; set; }
        public virtual Gender1 Gender { get; set; }
        public virtual Region Region { get; set; }
    }
}
