//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMS_Authontication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Enum_Requests
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Enum_Requests()
        {
            this.ApprovalDetails = new HashSet<ApprovalDetail>();
        }
    
        public long ID { get; set; }
        public string DESCRIPTION { get; set; }
        public string TYPE { get; set; }
        public string CARD_ID { get; set; }
        public Nullable<System.DateTime> REQ_DATE { get; set; }
        public string TITEL { get; set; }
        public string EMP_ENAME { get; set; }
        public string REQ_TYPE { get; set; }
        public Nullable<int> STATE { get; set; }
        public string NOTES { get; set; }
        public string REQUEST_TYP { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
        public string REPLAYED_BY { get; set; }
        public Nullable<System.DateTime> REPLAYED_DATE { get; set; }
        public string APPROVAL_IMAGE { get; set; }
        public string SERV_PROVIDER { get; set; }
        public Nullable<double> APPROV_VALUE { get; set; }
        public string CONF_NOTS { get; set; }
        public string REPLAY { get; set; }
        public string CHANG_EMP_NAME { get; set; }
        public string PR_CODE { get; set; }
        public string BR_CODE { get; set; }
        public string TYP_ANAME { get; set; }
        public string PR_ENAME { get; set; }
        public string MAIL_SEND { get; set; }
        public string APPROVALE_CODE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ApprovalDetail> ApprovalDetails { get; set; }
    }
}
