//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMS_Authontication1.Models
{
    using System;
    
    public partial class fn_AdminClamsList_Result1
    {
        public long Id { get; set; }
        public Nullable<long> Oracle_Id { get; set; }
        public string CardId { get; set; }
        public int CompanyPercent { get; set; }
        public Nullable<double> TotalValue { get; set; }
        public string Manager { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
    }
}
