//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMS_Authontication1.Models
{
    using System;
    
    public partial class fn_ClaimsReport_Result3
    {
        public Nullable<long> Id { get; set; }
        public string CardId { get; set; }
        public string EMP_ENAME { get; set; }
        public string Manager { get; set; }
        public Nullable<double> TotalValue { get; set; }
        public Nullable<double> TotalLocal { get; set; }
        public Nullable<double> TotalLocalDiscount { get; set; }
        public Nullable<double> TotalLocalDevlopment { get; set; }
        public Nullable<double> TotalImport { get; set; }
        public Nullable<double> TotalImportDiscount { get; set; }
        public Nullable<double> TotalImportDevelopment { get; set; }
        public Nullable<double> OverInsurance { get; set; }
        public double CompanyPayment { get; set; }
        public double PersonPayment { get; set; }
        public Nullable<double> Cash { get; set; }
    }
}
