//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMS_Authontication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HospitalClaim
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HospitalClaim()
        {
            this.HospitalClaimQRs = new HashSet<HospitalClaimQR>();
        }
    
        public long IdPrimary { get; set; }
        public long ID { get; set; }
        public Nullable<int> C_COMP_ID { get; set; }
        public Nullable<int> PROVIDER_CODE { get; set; }
        public string CARD_ID { get; set; }
        public string SERVICE_CODE { get; set; }
        public string SERVICES { get; set; }
        public string REQUEST_NUM { get; set; }
        public string CLASS_CODE { get; set; }
        public Nullable<int> CONTRACT_NO { get; set; }
        public Nullable<int> SERV_TYP { get; set; }
        public string CLAIM_NO { get; set; }
        public string NATIONAL_ID { get; set; }
        public string PHONE { get; set; }
        public Nullable<double> COMP_PERC { get; set; }
        public Nullable<double> CASH { get; set; }
        public Nullable<double> TOTAL_VALUE { get; set; }
        public Nullable<double> OVER_INSURANCE { get; set; }
        public Nullable<double> TOTAL_CASH { get; set; }
        public Nullable<double> PERSON_PAYMENT { get; set; }
        public Nullable<double> COMPANY_PAYMENT { get; set; }
        public string Note { get; set; }
        public string DoctorName { get; set; }
        public Nullable<int> SpecialistId { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<bool> IsSync { get; set; }
        public Nullable<System.DateTime> SyncDate { get; set; }
        public string SyncBy { get; set; }
        public Nullable<int> CompHolderCode { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HospitalClaimQR> HospitalClaimQRs { get; set; }
    }
}
