//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMS_Authontication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HospitalService
    {
        public long Id { get; set; }
        public string MainServiceCode { get; set; }
        public string ServiceCode { get; set; }
        public string HospitalCode { get; set; }
        public string MainServiceArName { get; set; }
        public string MainServiceEnName { get; set; }
        public string ServiceArName { get; set; }
        public string ServiceEnName { get; set; }
        public string GroupType { get; set; }
        public Nullable<double> Price { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<bool> IsCoverd { get; set; }
    }
}
