//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMS_Authontication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HospitalDoctor
    {
        public long Id { get; set; }
        public string DoctorName { get; set; }
        public string Degree { get; set; }
        public string Speciality { get; set; }
        public string ServiceType { get; set; }
        public string ProviderId { get; set; }
    }
}
