//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMS_Authontication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Indemnity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Indemnity()
        {
            this.IndemnityCardsServices = new HashSet<IndemnityCardsService>();
        }
    
        public long BatchID { get; set; }
        public string CardID { get; set; }
        public string EmployeeName { get; set; }
        public string CompanyName { get; set; }
        public Nullable<long> NationalID { get; set; }
        public string BankName { get; set; }
        public string BankBranch { get; set; }
        public long BankAccount { get; set; }
        public Nullable<bool> Type { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string UpdateBy { get; set; }
        public string DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<bool> Status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IndemnityCardsService> IndemnityCardsServices { get; set; }
    }
}
