//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMS_Authontication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IndemnityService
    {
        public int Id { get; set; }
        public int ServiceId { get; set; }
        public double Value { get; set; }
        public System.DateTime ServiceDate { get; set; }
        public long IndemnityCardsServicesId { get; set; }
    
        public virtual IndemnityCardsService IndemnityCardsService { get; set; }
        public virtual Service Service { get; set; }
    }
}
