//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMS_Authontication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IndemnityCardsService
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public IndemnityCardsService()
        {
            this.IndemnityServices = new HashSet<IndemnityService>();
        }
    
        public long Id { get; set; }
        public string CardId { get; set; }
        public string AttachPDF { get; set; }
        public long IndemnityId { get; set; }
    
        public virtual Indemnity Indemnity { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IndemnityService> IndemnityServices { get; set; }
    }
}
