//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMS_Authontication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IndemnityServiceMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public IndemnityServiceMaster()
        {
            this.IndemnityServiceFiles = new HashSet<IndemnityServiceFile>();
        }
    
        public int Id { get; set; }
        public Nullable<int> ServiceId { get; set; }
        public Nullable<int> SpecialistId { get; set; }
        public Nullable<System.DateTime> ServiceDate { get; set; }
        public Nullable<double> Value { get; set; }
        public Nullable<int> MasterIdFK { get; set; }
        public string ServiceCard { get; set; }
    
        public virtual IndemnityMaster IndemnityMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IndemnityServiceFile> IndemnityServiceFiles { get; set; }
        public virtual Service Service { get; set; }
        public virtual Specialities1 Specialities1 { get; set; }
    }
}
