//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMS_Authontication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Med_Card
    {
        public long Id { get; set; }
        public string CARD_NO { get; set; }
        public Nullable<int> PROVIDER_CODE { get; set; }
        public Nullable<int> C_COMP_ID { get; set; }
        public string NOTES { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
        public string UPDATE_BY { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public Nullable<System.DateTime> MONTH_START_DATE { get; set; }
        public Nullable<System.DateTime> MONTH_END_DATE { get; set; }
        public Nullable<int> GROUP_ID { get; set; }
        public string GROUP_NAME { get; set; }
        public Nullable<int> LOOK_01 { get; set; }
        public Nullable<int> SEQ { get; set; }
        public Nullable<int> PROVIDER_CODE_OLD { get; set; }
        public string TASHKHES_01 { get; set; }
        public Nullable<int> NO_PAY { get; set; }
        public Nullable<int> NO_OVER { get; set; }
        public Nullable<int> ST_DAY { get; set; }
        public Nullable<bool> IsSync { get; set; }
        public Nullable<System.DateTime> SyncDate { get; set; }
        public string SyncBy { get; set; }
    }
}
