//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMS_Authontication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Med_Medicine
    {
        public int Id { get; set; }
        public string MED_CODE { get; set; }
        public string CARD_NO { get; set; }
        public Nullable<System.DateTime> RDATE { get; set; }
        public Nullable<int> MED_TYP { get; set; }
        public Nullable<int> DOSE { get; set; }
        public Nullable<int> NO_OF_UINT { get; set; }
        public Nullable<double> TOTAL_AMT { get; set; }
        public Nullable<int> MED_DURATION { get; set; }
        public string TOT_DUR { get; set; }
        public Nullable<int> DOS_DUR { get; set; }
        public Nullable<double> EXCESS { get; set; }
        public Nullable<int> PACK_SIZE { get; set; }
        public Nullable<double> PACK_PRICE { get; set; }
        public string CON_MED { get; set; }
        public Nullable<int> UNIT_NO { get; set; }
        public Nullable<double> UNIT_PRICE { get; set; }
        public string MED_NAME { get; set; }
        public string DOSAGE_FORM { get; set; }
        public string NOTES { get; set; }
        public string ACTIVE { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
        public string UPDATE_BY { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public string ACT_MONTH { get; set; }
        public Nullable<int> LFT_MONTH { get; set; }
        public Nullable<System.DateTime> MONTH_DATE_STOP { get; set; }
        public Nullable<bool> IsSync { get; set; }
        public Nullable<System.DateTime> SyncDate { get; set; }
        public string SyncBy { get; set; }
        public string MedicineNoPay { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public string PoolType { get; set; }
    }
}
