//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMS_Authontication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MedicineData
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MedicineData()
        {
            this.MedicinesDiagnosis = new HashSet<MedicinesDiagnosi>();
        }
    
        public int Id { get; set; }
        public int BRANCH_CODE { get; set; }
        public Nullable<int> COMP_ID { get; set; }
        public string M_CODE { get; set; }
        public string LIC_TYPE { get; set; }
        public string MED_GROUP { get; set; }
        public string TRADE_NAME { get; set; }
        public string DOSAGE_FORM { get; set; }
        public Nullable<double> PACK_SIZE { get; set; }
        public Nullable<double> PACK_PRICE { get; set; }
        public string M_TYPE { get; set; }
        public string CON_MED { get; set; }
        public Nullable<int> UNIT_NO { get; set; }
        public Nullable<double> UNIT_PRICE { get; set; }
        public string ACTIVE { get; set; }
        public string UPDATE_BY { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
        public string GRN_CODE { get; set; }
        public Nullable<int> DiagnoiseGender { get; set; }
        public string DiagnoiseAge { get; set; }
        public Nullable<bool> IsCovered { get; set; }
        public Nullable<bool> IsSync { get; set; }
        public Nullable<System.DateTime> SyncDate { get; set; }
        public string SyncBy { get; set; }
        public string GroupType { get; set; }
    
        public virtual MedicineData MedicineData1 { get; set; }
        public virtual MedicineData MedicineData2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MedicinesDiagnosi> MedicinesDiagnosis { get; set; }
    }
}
