//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMS_Authontication1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DMS_TESTEntities : DbContext
    {
        public DMS_TESTEntities()
            : base("name=DMS_TESTEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Acception> Acceptions { get; set; }
        public virtual DbSet<AcceptionReason> AcceptionReasons { get; set; }
        public virtual DbSet<Basic_Data> Basic_Data { get; set; }
        public virtual DbSet<CardAcceptionReason> CardAcceptionReasons { get; set; }
        public virtual DbSet<COMP_CUSTOMIZED_D> COMP_CUSTOMIZED_D { get; set; }
        public virtual DbSet<Comp_Customized_D_D> Comp_Customized_D_D { get; set; }
        public virtual DbSet<Comp_Customized_D_D_Emp> Comp_Customized_D_D_Emp { get; set; }
        public virtual DbSet<COMP_CUSTOMIZED_D_EMP> COMP_CUSTOMIZED_D_EMP { get; set; }
        public virtual DbSet<Comp_Employees> Comp_Employees { get; set; }
        public virtual DbSet<Company_Cost_Center> Company_Cost_Center { get; set; }
        public virtual DbSet<CompContractClass> CompContractClasses { get; set; }
        public virtual DbSet<ContactU> ContactUs { get; set; }
        public virtual DbSet<Contract_Comp> Contract_Comp { get; set; }
        public virtual DbSet<Contract_Data> Contract_Data { get; set; }
        public virtual DbSet<DailyPermission> DailyPermissions { get; set; }
        public virtual DbSet<Diagnosi> Diagnosis { get; set; }
        public virtual DbSet<Employee_Request_Type> Employee_Request_Type { get; set; }
        public virtual DbSet<EmployeeRelation> EmployeeRelations { get; set; }
        public virtual DbSet<Gender> Genders { get; set; }
        public virtual DbSet<Governate> Governates { get; set; }
        public virtual DbSet<Indemnity> Indemnities { get; set; }
        public virtual DbSet<IndemnityCardsService> IndemnityCardsServices { get; set; }
        public virtual DbSet<IndemnityService> IndemnityServices { get; set; }
        public virtual DbSet<Insurance_Class> Insurance_Class { get; set; }
        public virtual DbSet<LicenseType> LicenseTypes { get; set; }
        public virtual DbSet<Med_Medicine> Med_Medicine { get; set; }
        public virtual DbSet<MedicineData> MedicineDatas { get; set; }
        public virtual DbSet<MedicineGroup> MedicineGroups { get; set; }
        public virtual DbSet<MedicinesDiagnosi> MedicinesDiagnosis { get; set; }
        public virtual DbSet<MedicineType> MedicineTypes { get; set; }
        public virtual DbSet<MonthlyPermission> MonthlyPermissions { get; set; }
        public virtual DbSet<Name_Lab> Name_Lab { get; set; }
        public virtual DbSet<Name_Lab_Cen> Name_Lab_Cen { get; set; }
        public virtual DbSet<Name_Ray> Name_Ray { get; set; }
        public virtual DbSet<Name_Ray_Cen> Name_Ray_Cen { get; set; }
        public virtual DbSet<Notification> Notifications { get; set; }
        public virtual DbSet<Patch> Patchs { get; set; }
        public virtual DbSet<Pr_Bra> Pr_Bra { get; set; }
        public virtual DbSet<Provider> Providers { get; set; }
        public virtual DbSet<ProviderTypeNew> ProviderTypeNews { get; set; }
        public virtual DbSet<RelationShip> RelationShips { get; set; }
        public virtual DbSet<RoshitaPharmcyApproved> RoshitaPharmcyApproveds { get; set; }
        public virtual DbSet<S_Ent_7> S_Ent_7 { get; set; }
        public virtual DbSet<Ser_Prov_Disc> Ser_Prov_Disc { get; set; }
        public virtual DbSet<SERV_PROVIDERS_NEW> SERV_PROVIDERS_NEW { get; set; }
        public virtual DbSet<Serv_Providers1> Serv_Providers1 { get; set; }
        public virtual DbSet<Service> Services { get; set; }
        public virtual DbSet<Specialities1> Specialities1 { get; set; }
        public virtual DbSet<HrAdminCompany> HrAdminCompanies { get; set; }
        public virtual DbSet<Department> Departments { get; set; }
        public virtual DbSet<DMSComplaint> DMSComplaints { get; set; }
        public virtual DbSet<ProviderComplaint> ProviderComplaints { get; set; }
        public virtual DbSet<RoshitaDetail> RoshitaDetails { get; set; }
        public virtual DbSet<SERVICE1> SERVICES1 { get; set; }
        public virtual DbSet<DoctorSpecialist> DoctorSpecialists { get; set; }
        public virtual DbSet<AfterSale> AfterSales { get; set; }
        public virtual DbSet<EmployeePersonalData> EmployeePersonalDatas { get; set; }
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<Gender1> Gender1 { get; set; }
        public virtual DbSet<Region> Regions { get; set; }
        public virtual DbSet<Co_Insurance_01> Co_Insurance_01 { get; set; }
        public virtual DbSet<Group_Lab> Group_Lab { get; set; }
        public virtual DbSet<Group_Ray> Group_Ray { get; set; }
        public virtual DbSet<ApprovalDetail> ApprovalDetails { get; set; }
        public virtual DbSet<ApprovalMaster> ApprovalMasters { get; set; }
        public virtual DbSet<ProviderEmail> ProviderEmails { get; set; }
        public virtual DbSet<EmployeesSMSCode> EmployeesSMSCodes { get; set; }
        public virtual DbSet<DosageForm> DosageForms { get; set; }
        public virtual DbSet<ProviderServicesPermission> ProviderServicesPermissions { get; set; }
        public virtual DbSet<HospitalService> HospitalServices { get; set; }
        public virtual DbSet<HospitalDoctor> HospitalDoctors { get; set; }
        public virtual DbSet<CronaEmergancy> CronaEmergancies { get; set; }
        public virtual DbSet<RoshitaAcception> RoshitaAcceptions { get; set; }
        public virtual DbSet<Enum_Requests> Enum_Requests { get; set; }
        public virtual DbSet<Employee_Request> Employee_Request { get; set; }
        public virtual DbSet<Serv_Lab> Serv_Lab { get; set; }
        public virtual DbSet<Serv_Ray> Serv_Ray { get; set; }
        public virtual DbSet<CompContractClassEmp> CompContractClassEmps { get; set; }
        public virtual DbSet<IndemnityMaster> IndemnityMasters { get; set; }
        public virtual DbSet<IndemnityNationalFile> IndemnityNationalFiles { get; set; }
        public virtual DbSet<IndemnityServiceFile> IndemnityServiceFiles { get; set; }
        public virtual DbSet<IndemnityServiceMaster> IndemnityServiceMasters { get; set; }
        public virtual DbSet<Roshita> Roshitas { get; set; }
        public virtual DbSet<RoshitaDiagnosisAdmin> RoshitaDiagnosisAdmins { get; set; }
        public virtual DbSet<ERPModule> ERPModules { get; set; }
        public virtual DbSet<ERPModulesPage> ERPModulesPages { get; set; }
        public virtual DbSet<ERPRolesModulesPage> ERPRolesModulesPages { get; set; }
        public virtual DbSet<ERPUsersModulesPage> ERPUsersModulesPages { get; set; }
        public virtual DbSet<ProposalBasicData> ProposalBasicDatas { get; set; }
        public virtual DbSet<ProposalBenefit> ProposalBenefits { get; set; }
        public virtual DbSet<ProposalBenefitsType> ProposalBenefitsTypes { get; set; }
        public virtual DbSet<ProposalClass> ProposalClasses { get; set; }
        public virtual DbSet<ProposalClassRelation> ProposalClassRelations { get; set; }
        public virtual DbSet<ProposalComment> ProposalComments { get; set; }
        public virtual DbSet<ProposalRenewalSummary> ProposalRenewalSummaries { get; set; }
        public virtual DbSet<APPROVAL_BAD> APPROVAL_BAD { get; set; }
        public virtual DbSet<COMP_CUSTOMIZED_D_D_MED> COMP_CUSTOMIZED_D_D_MED { get; set; }
        public virtual DbSet<COMP_CUSTOMIZED_D_D_MED_EMP> COMP_CUSTOMIZED_D_D_MED_EMP { get; set; }
        public virtual DbSet<HospitalClaim> HospitalClaims { get; set; }
        public virtual DbSet<DeliveryRequestDetail> DeliveryRequestDetails { get; set; }
        public virtual DbSet<DeliveryRequest> DeliveryRequests { get; set; }
        public virtual DbSet<PrescriptionRoshitaDignosi> PrescriptionRoshitaDignosis { get; set; }
        public virtual DbSet<EmployeeData> EmployeeDatas { get; set; }
        public virtual DbSet<RequestAddProvider> RequestAddProviders { get; set; }
        public virtual DbSet<RoshitaNoOverNoPay> RoshitaNoOverNoPays { get; set; }
        public virtual DbSet<CardUsed> CardUseds { get; set; }
        public virtual DbSet<UsersInternalCode> UsersInternalCodes { get; set; }
        public virtual DbSet<CompanyContractPhoto> CompanyContractPhotoes { get; set; }
        public virtual DbSet<ProviderContractPhoto> ProviderContractPhotoes { get; set; }
        public virtual DbSet<CompStatement> CompStatements { get; set; }
        public virtual DbSet<RemainConsumption> RemainConsumptions { get; set; }
        public virtual DbSet<ProviderContract> ProviderContracts { get; set; }
        public virtual DbSet<UserCompanyPermission> UserCompanyPermissions { get; set; }
        public virtual DbSet<Med_Card> Med_Card { get; set; }
        public virtual DbSet<Swap> Swaps { get; set; }
        public virtual DbSet<ProviderBlock> ProviderBlocks { get; set; }
        public virtual DbSet<ApprovalBil> ApprovalBils { get; set; }
        public virtual DbSet<CONSUMPTION_POOL> CONSUMPTION_POOL { get; set; }
    
        [DbFunction("DMS_TESTEntities", "fn_GetEmployessForCompany")]
        public virtual IQueryable<fn_GetEmployessForCompany_Result> fn_GetEmployessForCompany(Nullable<int> companyId, Nullable<int> maxContract, string tERMINATE_FLAG, string search)
        {
            var companyIdParameter = companyId.HasValue ?
                new ObjectParameter("CompanyId", companyId) :
                new ObjectParameter("CompanyId", typeof(int));
    
            var maxContractParameter = maxContract.HasValue ?
                new ObjectParameter("MaxContract", maxContract) :
                new ObjectParameter("MaxContract", typeof(int));
    
            var tERMINATE_FLAGParameter = tERMINATE_FLAG != null ?
                new ObjectParameter("TERMINATE_FLAG", tERMINATE_FLAG) :
                new ObjectParameter("TERMINATE_FLAG", typeof(string));
    
            var searchParameter = search != null ?
                new ObjectParameter("Search", search) :
                new ObjectParameter("Search", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fn_GetEmployessForCompany_Result>("[DMS_TESTEntities].[fn_GetEmployessForCompany](@CompanyId, @MaxContract, @TERMINATE_FLAG, @Search)", companyIdParameter, maxContractParameter, tERMINATE_FLAGParameter, searchParameter);
        }
    
        [DbFunction("DMS_TESTEntities", "fn_AdminClamsCounts")]
        public virtual IQueryable<fn_AdminClamsCounts_Result> fn_AdminClamsCounts(string fROM, string tO, string company, string provider, string branch, string approvalNo, string cardId, string tYPE)
        {
            var fROMParameter = fROM != null ?
                new ObjectParameter("FROM", fROM) :
                new ObjectParameter("FROM", typeof(string));
    
            var tOParameter = tO != null ?
                new ObjectParameter("TO", tO) :
                new ObjectParameter("TO", typeof(string));
    
            var companyParameter = company != null ?
                new ObjectParameter("Company", company) :
                new ObjectParameter("Company", typeof(string));
    
            var providerParameter = provider != null ?
                new ObjectParameter("Provider", provider) :
                new ObjectParameter("Provider", typeof(string));
    
            var branchParameter = branch != null ?
                new ObjectParameter("Branch", branch) :
                new ObjectParameter("Branch", typeof(string));
    
            var approvalNoParameter = approvalNo != null ?
                new ObjectParameter("ApprovalNo", approvalNo) :
                new ObjectParameter("ApprovalNo", typeof(string));
    
            var cardIdParameter = cardId != null ?
                new ObjectParameter("CardId", cardId) :
                new ObjectParameter("CardId", typeof(string));
    
            var tYPEParameter = tYPE != null ?
                new ObjectParameter("TYPE", tYPE) :
                new ObjectParameter("TYPE", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fn_AdminClamsCounts_Result>("[DMS_TESTEntities].[fn_AdminClamsCounts](@FROM, @TO, @Company, @Provider, @Branch, @ApprovalNo, @CardId, @TYPE)", fROMParameter, tOParameter, companyParameter, providerParameter, branchParameter, approvalNoParameter, cardIdParameter, tYPEParameter);
        }
    
        [DbFunction("DMS_TESTEntities", "fn_MedicalApprovalSearsh")]
        public virtual IQueryable<fn_MedicalApprovalSearsh_Result> fn_MedicalApprovalSearsh(string cardId, string dateFrom, string dateto, string code)
        {
            var cardIdParameter = cardId != null ?
                new ObjectParameter("CardId", cardId) :
                new ObjectParameter("CardId", typeof(string));
    
            var dateFromParameter = dateFrom != null ?
                new ObjectParameter("dateFrom", dateFrom) :
                new ObjectParameter("dateFrom", typeof(string));
    
            var datetoParameter = dateto != null ?
                new ObjectParameter("dateto", dateto) :
                new ObjectParameter("dateto", typeof(string));
    
            var codeParameter = code != null ?
                new ObjectParameter("Code", code) :
                new ObjectParameter("Code", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fn_MedicalApprovalSearsh_Result>("[DMS_TESTEntities].[fn_MedicalApprovalSearsh](@CardId, @dateFrom, @dateto, @Code)", cardIdParameter, dateFromParameter, datetoParameter, codeParameter);
        }
    
        [DbFunction("DMS_TESTEntities", "fn_AdminClamsList")]
        public virtual IQueryable<fn_AdminClamsList_Result3> fn_AdminClamsList(string fROM, string tO, string company, string provider, string branch, string approvalNo, string cardId, string tYPE)
        {
            var fROMParameter = fROM != null ?
                new ObjectParameter("FROM", fROM) :
                new ObjectParameter("FROM", typeof(string));
    
            var tOParameter = tO != null ?
                new ObjectParameter("TO", tO) :
                new ObjectParameter("TO", typeof(string));
    
            var companyParameter = company != null ?
                new ObjectParameter("Company", company) :
                new ObjectParameter("Company", typeof(string));
    
            var providerParameter = provider != null ?
                new ObjectParameter("Provider", provider) :
                new ObjectParameter("Provider", typeof(string));
    
            var branchParameter = branch != null ?
                new ObjectParameter("Branch", branch) :
                new ObjectParameter("Branch", typeof(string));
    
            var approvalNoParameter = approvalNo != null ?
                new ObjectParameter("ApprovalNo", approvalNo) :
                new ObjectParameter("ApprovalNo", typeof(string));
    
            var cardIdParameter = cardId != null ?
                new ObjectParameter("CardId", cardId) :
                new ObjectParameter("CardId", typeof(string));
    
            var tYPEParameter = tYPE != null ?
                new ObjectParameter("TYPE", tYPE) :
                new ObjectParameter("TYPE", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fn_AdminClamsList_Result3>("[DMS_TESTEntities].[fn_AdminClamsList](@FROM, @TO, @Company, @Provider, @Branch, @ApprovalNo, @CardId, @TYPE)", fROMParameter, tOParameter, companyParameter, providerParameter, branchParameter, approvalNoParameter, cardIdParameter, tYPEParameter);
        }
    
        [DbFunction("DMS_TESTEntities", "fn_ClaimsReport")]
        public virtual IQueryable<fn_ClaimsReport_Result3> fn_ClaimsReport(string from, string to, string provider)
        {
            var fromParameter = from != null ?
                new ObjectParameter("from", from) :
                new ObjectParameter("from", typeof(string));
    
            var toParameter = to != null ?
                new ObjectParameter("to", to) :
                new ObjectParameter("to", typeof(string));
    
            var providerParameter = provider != null ?
                new ObjectParameter("provider", provider) :
                new ObjectParameter("provider", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fn_ClaimsReport_Result3>("[DMS_TESTEntities].[fn_ClaimsReport](@from, @to, @provider)", fromParameter, toParameter, providerParameter);
        }
    
        [DbFunction("DMS_TESTEntities", "fn_AdminLabClamsCounts")]
        public virtual IQueryable<fn_AdminLabClamsCounts_Result> fn_AdminLabClamsCounts(string fROM, string tO, string company, string provider, string branch, string approvalNo, string cardId, string tYPE)
        {
            var fROMParameter = fROM != null ?
                new ObjectParameter("FROM", fROM) :
                new ObjectParameter("FROM", typeof(string));
    
            var tOParameter = tO != null ?
                new ObjectParameter("TO", tO) :
                new ObjectParameter("TO", typeof(string));
    
            var companyParameter = company != null ?
                new ObjectParameter("Company", company) :
                new ObjectParameter("Company", typeof(string));
    
            var providerParameter = provider != null ?
                new ObjectParameter("Provider", provider) :
                new ObjectParameter("Provider", typeof(string));
    
            var branchParameter = branch != null ?
                new ObjectParameter("Branch", branch) :
                new ObjectParameter("Branch", typeof(string));
    
            var approvalNoParameter = approvalNo != null ?
                new ObjectParameter("ApprovalNo", approvalNo) :
                new ObjectParameter("ApprovalNo", typeof(string));
    
            var cardIdParameter = cardId != null ?
                new ObjectParameter("CardId", cardId) :
                new ObjectParameter("CardId", typeof(string));
    
            var tYPEParameter = tYPE != null ?
                new ObjectParameter("TYPE", tYPE) :
                new ObjectParameter("TYPE", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fn_AdminLabClamsCounts_Result>("[DMS_TESTEntities].[fn_AdminLabClamsCounts](@FROM, @TO, @Company, @Provider, @Branch, @ApprovalNo, @CardId, @TYPE)", fROMParameter, tOParameter, companyParameter, providerParameter, branchParameter, approvalNoParameter, cardIdParameter, tYPEParameter);
        }
    
        [DbFunction("DMS_TESTEntities", "fn_AdminLabClamsList")]
        public virtual IQueryable<fn_AdminLabClamsList_Result> fn_AdminLabClamsList(string fROM, string tO, string company, string provider, string branch, string approvalNo, string cardId, string tYPE)
        {
            var fROMParameter = fROM != null ?
                new ObjectParameter("FROM", fROM) :
                new ObjectParameter("FROM", typeof(string));
    
            var tOParameter = tO != null ?
                new ObjectParameter("TO", tO) :
                new ObjectParameter("TO", typeof(string));
    
            var companyParameter = company != null ?
                new ObjectParameter("Company", company) :
                new ObjectParameter("Company", typeof(string));
    
            var providerParameter = provider != null ?
                new ObjectParameter("Provider", provider) :
                new ObjectParameter("Provider", typeof(string));
    
            var branchParameter = branch != null ?
                new ObjectParameter("Branch", branch) :
                new ObjectParameter("Branch", typeof(string));
    
            var approvalNoParameter = approvalNo != null ?
                new ObjectParameter("ApprovalNo", approvalNo) :
                new ObjectParameter("ApprovalNo", typeof(string));
    
            var cardIdParameter = cardId != null ?
                new ObjectParameter("CardId", cardId) :
                new ObjectParameter("CardId", typeof(string));
    
            var tYPEParameter = tYPE != null ?
                new ObjectParameter("TYPE", tYPE) :
                new ObjectParameter("TYPE", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fn_AdminLabClamsList_Result>("[DMS_TESTEntities].[fn_AdminLabClamsList](@FROM, @TO, @Company, @Provider, @Branch, @ApprovalNo, @CardId, @TYPE)", fROMParameter, tOParameter, companyParameter, providerParameter, branchParameter, approvalNoParameter, cardIdParameter, tYPEParameter);
        }
    
        [DbFunction("DMS_TESTEntities", "fn_AdminRayClamsCounts")]
        public virtual IQueryable<fn_AdminRayClamsCounts_Result> fn_AdminRayClamsCounts(string fROM, string tO, string company, string provider, string branch, string approvalNo, string cardId, string tYPE)
        {
            var fROMParameter = fROM != null ?
                new ObjectParameter("FROM", fROM) :
                new ObjectParameter("FROM", typeof(string));
    
            var tOParameter = tO != null ?
                new ObjectParameter("TO", tO) :
                new ObjectParameter("TO", typeof(string));
    
            var companyParameter = company != null ?
                new ObjectParameter("Company", company) :
                new ObjectParameter("Company", typeof(string));
    
            var providerParameter = provider != null ?
                new ObjectParameter("Provider", provider) :
                new ObjectParameter("Provider", typeof(string));
    
            var branchParameter = branch != null ?
                new ObjectParameter("Branch", branch) :
                new ObjectParameter("Branch", typeof(string));
    
            var approvalNoParameter = approvalNo != null ?
                new ObjectParameter("ApprovalNo", approvalNo) :
                new ObjectParameter("ApprovalNo", typeof(string));
    
            var cardIdParameter = cardId != null ?
                new ObjectParameter("CardId", cardId) :
                new ObjectParameter("CardId", typeof(string));
    
            var tYPEParameter = tYPE != null ?
                new ObjectParameter("TYPE", tYPE) :
                new ObjectParameter("TYPE", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fn_AdminRayClamsCounts_Result>("[DMS_TESTEntities].[fn_AdminRayClamsCounts](@FROM, @TO, @Company, @Provider, @Branch, @ApprovalNo, @CardId, @TYPE)", fROMParameter, tOParameter, companyParameter, providerParameter, branchParameter, approvalNoParameter, cardIdParameter, tYPEParameter);
        }
    
        [DbFunction("DMS_TESTEntities", "fn_AdminRayClamsList")]
        public virtual IQueryable<fn_AdminRayClamsList_Result> fn_AdminRayClamsList(string fROM, string tO, string company, string provider, string branch, string approvalNo, string cardId, string tYPE)
        {
            var fROMParameter = fROM != null ?
                new ObjectParameter("FROM", fROM) :
                new ObjectParameter("FROM", typeof(string));
    
            var tOParameter = tO != null ?
                new ObjectParameter("TO", tO) :
                new ObjectParameter("TO", typeof(string));
    
            var companyParameter = company != null ?
                new ObjectParameter("Company", company) :
                new ObjectParameter("Company", typeof(string));
    
            var providerParameter = provider != null ?
                new ObjectParameter("Provider", provider) :
                new ObjectParameter("Provider", typeof(string));
    
            var branchParameter = branch != null ?
                new ObjectParameter("Branch", branch) :
                new ObjectParameter("Branch", typeof(string));
    
            var approvalNoParameter = approvalNo != null ?
                new ObjectParameter("ApprovalNo", approvalNo) :
                new ObjectParameter("ApprovalNo", typeof(string));
    
            var cardIdParameter = cardId != null ?
                new ObjectParameter("CardId", cardId) :
                new ObjectParameter("CardId", typeof(string));
    
            var tYPEParameter = tYPE != null ?
                new ObjectParameter("TYPE", tYPE) :
                new ObjectParameter("TYPE", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fn_AdminRayClamsList_Result>("[DMS_TESTEntities].[fn_AdminRayClamsList](@FROM, @TO, @Company, @Provider, @Branch, @ApprovalNo, @CardId, @TYPE)", fROMParameter, tOParameter, companyParameter, providerParameter, branchParameter, approvalNoParameter, cardIdParameter, tYPEParameter);
        }
    
        [DbFunction("DMS_TESTEntities", "fn_searchCompEmployees")]
        public virtual IQueryable<fn_searchCompEmployees_Result> fn_searchCompEmployees(string search)
        {
            var searchParameter = search != null ?
                new ObjectParameter("search", search) :
                new ObjectParameter("search", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fn_searchCompEmployees_Result>("[DMS_TESTEntities].[fn_searchCompEmployees](@search)", searchParameter);
        }
    
        [DbFunction("DMS_TESTEntities", "fn_consumption")]
        public virtual IQueryable<fn_consumption_Result> fn_consumption(string id, Nullable<long> serviceCode)
        {
            var idParameter = id != null ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(string));
    
            var serviceCodeParameter = serviceCode.HasValue ?
                new ObjectParameter("ServiceCode", serviceCode) :
                new ObjectParameter("ServiceCode", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fn_consumption_Result>("[DMS_TESTEntities].[fn_consumption](@id, @ServiceCode)", idParameter, serviceCodeParameter);
        }
    
        [DbFunction("DMS_TESTEntities", "fn_consumption_update")]
        public virtual IQueryable<fn_consumption_update_Result> fn_consumption_update(string id, Nullable<long> serviceCode, Nullable<long> roshita_id)
        {
            var idParameter = id != null ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(string));
    
            var serviceCodeParameter = serviceCode.HasValue ?
                new ObjectParameter("ServiceCode", serviceCode) :
                new ObjectParameter("ServiceCode", typeof(long));
    
            var roshita_idParameter = roshita_id.HasValue ?
                new ObjectParameter("Roshita_id", roshita_id) :
                new ObjectParameter("Roshita_id", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fn_consumption_update_Result>("[DMS_TESTEntities].[fn_consumption_update](@id, @ServiceCode, @Roshita_id)", idParameter, serviceCodeParameter, roshita_idParameter);
        }
    
        [DbFunction("DMS_TESTEntities", "fn_StopEditAdminClamsList")]
        public virtual IQueryable<fn_StopEditAdminClamsList_Result> fn_StopEditAdminClamsList(string fROM, string tO, string company, string provider, string branch, string approvalNo, string cardId, string tYPE)
        {
            var fROMParameter = fROM != null ?
                new ObjectParameter("FROM", fROM) :
                new ObjectParameter("FROM", typeof(string));
    
            var tOParameter = tO != null ?
                new ObjectParameter("TO", tO) :
                new ObjectParameter("TO", typeof(string));
    
            var companyParameter = company != null ?
                new ObjectParameter("Company", company) :
                new ObjectParameter("Company", typeof(string));
    
            var providerParameter = provider != null ?
                new ObjectParameter("Provider", provider) :
                new ObjectParameter("Provider", typeof(string));
    
            var branchParameter = branch != null ?
                new ObjectParameter("Branch", branch) :
                new ObjectParameter("Branch", typeof(string));
    
            var approvalNoParameter = approvalNo != null ?
                new ObjectParameter("ApprovalNo", approvalNo) :
                new ObjectParameter("ApprovalNo", typeof(string));
    
            var cardIdParameter = cardId != null ?
                new ObjectParameter("CardId", cardId) :
                new ObjectParameter("CardId", typeof(string));
    
            var tYPEParameter = tYPE != null ?
                new ObjectParameter("TYPE", tYPE) :
                new ObjectParameter("TYPE", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fn_StopEditAdminClamsList_Result>("[DMS_TESTEntities].[fn_StopEditAdminClamsList](@FROM, @TO, @Company, @Provider, @Branch, @ApprovalNo, @CardId, @TYPE)", fROMParameter, tOParameter, companyParameter, providerParameter, branchParameter, approvalNoParameter, cardIdParameter, tYPEParameter);
        }
    
        [DbFunction("DMS_TESTEntities", "fn_searchCompEmployeesForNextContract")]
        public virtual IQueryable<fn_searchCompEmployeesForNextContract_Result> fn_searchCompEmployeesForNextContract(string search)
        {
            var searchParameter = search != null ?
                new ObjectParameter("search", search) :
                new ObjectParameter("search", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fn_searchCompEmployeesForNextContract_Result>("[DMS_TESTEntities].[fn_searchCompEmployeesForNextContract](@search)", searchParameter);
        }
    }
}
