//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMS_Authontication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patch
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Patch()
        {
            this.Roshitas = new HashSet<Roshita>();
        }
    
        public int Id { get; set; }
        public Nullable<int> AmountOfClaimSubmitted { get; set; }
        public string ServiceProvider { get; set; }
        public Nullable<System.DateTime> ReceivedDate { get; set; }
        public Nullable<System.DateTime> ClaimDate { get; set; }
        public Nullable<int> ManualCount { get; set; }
        public Nullable<int> SystemCount { get; set; }
        public Nullable<int> ManualAmount { get; set; }
        public Nullable<int> SystemAmount { get; set; }
        public string ClaimType { get; set; }
        public string Status { get; set; }
        public string Groups { get; set; }
        public Nullable<int> ServicesOfTheMonth { get; set; }
        public Nullable<System.DateTime> AcceptingDate { get; set; }
        public Nullable<System.DateTime> StartFrom { get; set; }
        public Nullable<System.DateTime> EndAt { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<bool> IsSync { get; set; }
        public Nullable<System.DateTime> SyncDate { get; set; }
        public string SyncBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Roshita> Roshitas { get; set; }
    }
}
