//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMS_Authontication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PETROTRADE_EMPLOYEES
    {
        public string CARD_ID { get; set; }
        public Nullable<int> C_COMP_ID { get; set; }
        public string EMP_CODE { get; set; }
        public Nullable<int> CLASS_CODE { get; set; }
        public string EMP_ANAME { get; set; }
        public string COST_CENTER { get; set; }
        public string REF_ANAME { get; set; }
        public string REF_TYPE { get; set; }
        public string TEL1 { get; set; }
        public Nullable<System.DateTime> BIRTH_DATE { get; set; }
        public string INS_TYP { get; set; }
        public string GENDER { get; set; }
        public string NATIONAL_ID { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
        public string CREATED_BY { get; set; }
        public int Id { get; set; }
    }
}
