//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMS_Authontication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pr_Bra
    {
        public int Id { get; set; }
        public decimal PR_CODE { get; set; }
        public decimal COMP_ID { get; set; }
        public decimal BRANCH_CODE { get; set; }
        public decimal PRV_TYPE { get; set; }
        public string PR_ANAME { get; set; }
        public string PR_ENAME { get; set; }
        public string ADDRESS1 { get; set; }
        public string ADDRESS2 { get; set; }
        public string TEL1 { get; set; }
        public string TEL2 { get; set; }
        public string FAX { get; set; }
        public string EMAIL { get; set; }
        public Nullable<decimal> AREA_CODE { get; set; }
        public string PERSON1 { get; set; }
        public string PERSON2 { get; set; }
        public string PERSON1_TEL { get; set; }
        public string PERSON2_TEL { get; set; }
        public decimal BRA_CODE { get; set; }
        public Nullable<bool> IsSync { get; set; }
        public Nullable<System.DateTime> SyncDate { get; set; }
        public string SyncBy { get; set; }
    }
}
