//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMS_Authontication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pricing
    {
        public int Id { get; set; }
        public string Prices { get; set; }
        public int CategoriesCount { get; set; }
        public string UserId { get; set; }
        public int ProposalMainId { get; set; }
    
        public virtual ProposalMain ProposalMain { get; set; }
    }
}
