//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMS_Authontication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrintMedicalReport
    {
        public int Id { get; set; }
        public Nullable<int> CompNumber { get; set; }
        public string ProviderType { get; set; }
        public string Speciality { get; set; }
        public string CardId { get; set; }
        public string ProviderName { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
    }
}
