//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMS_Authontication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProposalBenefit
    {
        public int Id { get; set; }
        public int ProposalClassId { get; set; }
        public int TypeBenefitsId { get; set; }
        public int Match { get; set; }
    
        public virtual ProposalClass ProposalClass { get; set; }
    }
}
