//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMS_Authontication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProposalNotification
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProposalNotification()
        {
            this.ProposalNotificationApplicationUsers = new HashSet<ProposalNotificationApplicationUser>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public bool IsRead { get; set; }
        public bool IsDeleted { get; set; }
        public bool IsReminder { get; set; }
        public string SentTo { get; set; }
        public int ProposalMainId { get; set; }
        public string DetailsUrl { get; set; }
    
        public virtual ProposalMain ProposalMain { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProposalNotificationApplicationUser> ProposalNotificationApplicationUsers { get; set; }
    }
}
