//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMS_Authontication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProposalClass
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProposalClass()
        {
            this.ProposalBenefits = new HashSet<ProposalBenefit>();
            this.ProposalClassRelations = new HashSet<ProposalClassRelation>();
        }
    
        public int Id { get; set; }
        public int ProposalId { get; set; }
        public int NumProposal { get; set; }
        public string ClassCode { get; set; }
        public int NumMale { get; set; }
        public int NumFemael { get; set; }
        public int NumChronic { get; set; }
        public double TotalChronic { get; set; }
        public double Premium { get; set; }
        public double Max { get; set; }
        public Nullable<int> AgeFrom { get; set; }
        public string AgeFromType { get; set; }
        public Nullable<int> AgeTo { get; set; }
        public string AgeToType { get; set; }
        public Nullable<int> Gender { get; set; }
        public string Branch { get; set; }
    
        public virtual ProposalBasicData ProposalBasicData { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProposalBenefit> ProposalBenefits { get; set; }
        public virtual ProposalClass ProposalClass1 { get; set; }
        public virtual ProposalClass ProposalClass2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProposalClassRelation> ProposalClassRelations { get; set; }
    }
}
