//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMS_Authontication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProposalOutsideMedicalAuthority
    {
        public int Id { get; set; }
        public bool HospitalsResidenceServiceLimitOption { get; set; }
        public bool HospitalsResidenceServicePercentageoption { get; set; }
        public Nullable<decimal> HospitalsResidenceServiceLimit { get; set; }
        public Nullable<decimal> HospitalsResidenceServicePercentage { get; set; }
        public bool OutsideClinicsLimitOption { get; set; }
        public bool OutsideClinicsPercentageoption { get; set; }
        public Nullable<decimal> OutsideClinicsLimit { get; set; }
        public Nullable<decimal> OutsideClinicsPercentage { get; set; }
        public bool ExaminationAndAnalysisLimitOption { get; set; }
        public bool ExaminationAndAnalysisPercentageoption { get; set; }
        public Nullable<decimal> ExaminationAndAnalysisLimit { get; set; }
        public Nullable<decimal> ExaminationAndAnalysisPercentage { get; set; }
        public bool PhysicalTherapyLimitOption { get; set; }
        public bool PhysicalTherapyPercentageoption { get; set; }
        public Nullable<decimal> PhysicalTherapyLimit { get; set; }
        public Nullable<decimal> PhysicalTherapyPercentage { get; set; }
        public bool DailyTherapyLimitOption { get; set; }
        public bool DailyTherapyPercentageoption { get; set; }
        public Nullable<decimal> DailyTherapyLimit { get; set; }
        public Nullable<decimal> DailyTherapyPercentage { get; set; }
        public bool ChronicTherapyLimitOption { get; set; }
        public bool ChronicTherapyPercentageoption { get; set; }
        public Nullable<decimal> ChronicTherapyLimit { get; set; }
        public Nullable<decimal> ChronicTherapyPercentage { get; set; }
        public bool NatChildBirthLimitOption { get; set; }
        public bool NatChildBirthPercentageoption { get; set; }
        public Nullable<decimal> NatChildBirthLimit { get; set; }
        public Nullable<decimal> NatChildBirthPercentage { get; set; }
        public bool CaesChildBirthLimitOption { get; set; }
        public bool CaesChildBirthPercentageoption { get; set; }
        public Nullable<decimal> CaesChildBirthLimit { get; set; }
        public Nullable<decimal> CaesChildBirthPercentage { get; set; }
        public bool LegalAbortionLimitOption { get; set; }
        public bool LegalAbortionPercentageoption { get; set; }
        public Nullable<decimal> LegalAbortionLimit { get; set; }
        public Nullable<decimal> LegalAbortionPercentage { get; set; }
        public bool PregFollowUpLimitOption { get; set; }
        public bool PregFollowUpPercentageoption { get; set; }
        public Nullable<decimal> PregFollowUpLimit { get; set; }
        public Nullable<decimal> PregFollowUpPercentage { get; set; }
        public bool AdvancedDentalServiceLimitOption { get; set; }
        public bool AdvancedDentalServicePercentageoption { get; set; }
        public Nullable<decimal> AdvancedDentalServiceLimit { get; set; }
        public Nullable<decimal> AdvancedDentalServicePercentage { get; set; }
        public bool BasicDentalServiceLimitOption { get; set; }
        public bool BasicDentalServicePercentageoption { get; set; }
        public Nullable<decimal> BasicDentalServiceLimit { get; set; }
        public Nullable<decimal> BasicDentalServicePercentage { get; set; }
        public bool OpticsLimitOption { get; set; }
        public bool OpticsPercentageoption { get; set; }
        public Nullable<decimal> OpticsLimit { get; set; }
        public Nullable<decimal> OpticsPercentage { get; set; }
        public int IntensiveCareDaysCount { get; set; }
        public int DailyRoshitasCountPerMonth { get; set; }
        public bool CoronaVaccineCoverage { get; set; }
        public int ProposalMainId { get; set; }
        public int ClassCode { get; set; }
        public decimal DoctorsExaminationValue { get; set; }
        public int PricesOutsideMedicalAuthorityId { get; set; }
    
        public virtual ProposalMain ProposalMain { get; set; }
    }
}
