//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMS_Authontication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProposalBasicData
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProposalBasicData()
        {
            this.ProposalClasses = new HashSet<ProposalClass>();
        }
    
        public int Id { get; set; }
        public bool TypeProposal { get; set; }
        public bool InsuredBefore { get; set; }
        public bool ExClient { get; set; }
        public string CompName { get; set; }
        public Nullable<int> CompId { get; set; }
        public Nullable<int> ContractNo { get; set; }
        public bool InsuredOtherComp { get; set; }
        public int NumProposal { get; set; }
        public string Conclusion { get; set; }
        public string status { get; set; }
        public string OtherCompName { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string ClassType { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProposalClass> ProposalClasses { get; set; }
    }
}
