//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMS_Authontication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProposalMain
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProposalMain()
        {
            this.ProposalInsideMedicalAuthorities = new HashSet<ProposalInsideMedicalAuthority>();
            this.ProposalNotifications = new HashSet<ProposalNotification>();
            this.ProposalOutsideMedicalAuthorities = new HashSet<ProposalOutsideMedicalAuthority>();
            this.ProposalStepTwoes = new HashSet<ProposalStepTwo>();
        }
    
        public int Id { get; set; }
        public string CompanyEnglishName { get; set; }
        public string CompanyArabicName { get; set; }
        public string CompanyTelePhone { get; set; }
        public string AdministratorName { get; set; }
        public string AdministratorPhone { get; set; }
        public System.DateTime ContractDate { get; set; }
        public int DoctorVisitsCount { get; set; }
        public decimal DoctorVisitsDuration { get; set; }
        public string Email { get; set; }
        public bool InsuranceExists { get; set; }
        public int MedicationPoolVal { get; set; }
        public decimal MedicationPoolPercentage { get; set; }
        public int PrexPoolVal { get; set; }
        public decimal PrexPoolPercentage { get; set; }
        public int PrexPoolCoverage { get; set; }
        public int ExceptionPoolVal { get; set; }
        public decimal ExceptionPoolPercentage { get; set; }
        public int ExceptionPoolCoverage { get; set; }
        public int ChronicPoolVal { get; set; }
        public decimal ChronicPoolPercentage { get; set; }
        public int ChronicPoolCoverage { get; set; }
        public int CriticalPoolVal { get; set; }
        public decimal CriticalPoolPercentage { get; set; }
        public int CriticalPoolCoverage { get; set; }
        public int CategoriesCount { get; set; }
        public bool IsBroker { get; set; }
        public Nullable<int> BrokerId { get; set; }
        public Nullable<decimal> BrokerPercentage { get; set; }
        public string UserId { get; set; }
        public int CompanyActivityId { get; set; }
        public int AreaId { get; set; }
        public string ConsumptionFileName { get; set; }
        public string Code { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProposalInsideMedicalAuthority> ProposalInsideMedicalAuthorities { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProposalNotification> ProposalNotifications { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProposalOutsideMedicalAuthority> ProposalOutsideMedicalAuthorities { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProposalStepTwo> ProposalStepTwoes { get; set; }
    }
}
