//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMS_Authontication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProposalRenewalSummary
    {
        public int Id { get; set; }
        public int ProposalId { get; set; }
        public string Status { get; set; }
        public Nullable<int> LastLR { get; set; }
        public Nullable<int> RateIncrease { get; set; }
        public Nullable<int> NoSubscribersRate { get; set; }
        public Nullable<int> ExtraBenefits { get; set; }
        public Nullable<int> ExtraCopayment { get; set; }
        public Nullable<int> SpecialConditions { get; set; }
        public Nullable<int> Recommendations { get; set; }
        public Nullable<int> NoYears { get; set; }
        public Nullable<int> OntractCancelationPeriod { get; set; }
        public Nullable<int> Last3YearsLR { get; set; }
        public Nullable<int> last3YearRateIncrease { get; set; }
        public Nullable<int> Last3YearsChangeNoSubscribersStart { get; set; }
        public Nullable<int> Last3YearsChangeNoSubscribersCurrent { get; set; }
        public Nullable<int> PreviousControlMeasures { get; set; }
    }
}
