//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMS_Authontication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProviderContractPhoto
    {
        public int Id { get; set; }
        public Nullable<int> Code { get; set; }
        public Nullable<int> ProviderCode { get; set; }
        public string ProviderNameAr { get; set; }
        public Nullable<int> TypeImage { get; set; }
        public string NameType { get; set; }
        public string TypeContract { get; set; }
        public string TypeContractCopy { get; set; }
        public string Notes { get; set; }
        public string Path { get; set; }
        public string PathOriginal { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public string Active { get; set; }
    }
}
