//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMS_Authontication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProviderComplaint
    {
        public long Id { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public string Status { get; set; }
        public string SolveProblem { get; set; }
        public Nullable<System.DateTime> ProblemDate { get; set; }
        public Nullable<int> ProviderTypeId { get; set; }
        public Nullable<int> ProviderId { get; set; }
        public Nullable<long> BranchId { get; set; }
        public string Subject { get; set; }
        public string Problem { get; set; }
        public string PhoneNumber { get; set; }
        public string CompName { get; set; }
        public Nullable<bool> IsTechnical { get; set; }
    
        public virtual ProviderTypeNew ProviderTypeNew { get; set; }
        public virtual SERV_PROVIDERS_NEW SERV_PROVIDERS_NEW { get; set; }
        public virtual Serv_Providers1 Serv_Providers1 { get; set; }
    }
}
