//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMS_Authontication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RemainConsumption
    {
        public int Id { get; set; }
        public string CARD_ID { get; set; }
        public Nullable<int> CONTRACT_NO { get; set; }
        public Nullable<double> MAX_AMOUNT { get; set; }
        public Nullable<double> NET { get; set; }
        public Nullable<double> REMAINING { get; set; }
        public Nullable<bool> IsSync { get; set; }
        public string SyncBy { get; set; }
        public Nullable<System.DateTime> SyncDate { get; set; }
    }
}
