//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMS_Authontication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RenewalServicePool
    {
        public Nullable<int> MainId { get; set; }
        public Nullable<int> ServiceId { get; set; }
        public int Id { get; set; }
    
        public virtual PoolService PoolService { get; set; }
        public virtual RenewalBasicData RenewalBasicData { get; set; }
    }
}
