//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMS_Authontication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RenewalMain
    {
        public int Id { get; set; }
        public Nullable<long> CompId { get; set; }
        public Nullable<int> ContractNo { get; set; }
        public Nullable<int> ClassCount { get; set; }
        public Nullable<int> EmpCount { get; set; }
        public string UserId { get; set; }
        public string Code { get; set; }
    }
}
