//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMS_Authontication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RenewalBasicData
    {
        public int Id { get; set; }
        public Nullable<double> ValuePool { get; set; }
        public string PercentPool { get; set; }
        public Nullable<int> TypeCovarge { get; set; }
        public Nullable<double> StopLoss { get; set; }
        public Nullable<double> VisitorValue { get; set; }
        public Nullable<int> VisitorNumber { get; set; }
        public Nullable<int> VisitorType { get; set; }
        public Nullable<bool> IsBroker { get; set; }
        public Nullable<int> BrokerId { get; set; }
        public Nullable<int> BrokerPercentage { get; set; }
        public Nullable<double> IssuanceExpenses { get; set; }
        public Nullable<double> AdminExpenses { get; set; }
        public Nullable<int> MainId { get; set; }
    
        public virtual RenewalMain RenewalMain { get; set; }
    }
}
