//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMS_Authontication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RenewalStepTwo
    {
        public int Id { get; set; }
        public decimal AnnualCoverageCeiling { get; set; }
        public int ParticipantsCount { get; set; }
        public decimal Price { get; set; }
        public int MinAge { get; set; }
        public int MaxAge { get; set; }
        public int AvgAge { get; set; }
        public int ChecksInsideHospital { get; set; }
        public int PhysicalTherapyInsideHospital { get; set; }
        public int OutsideClincInsideHospital { get; set; }
        public int DentalServicesInsideHospital { get; set; }
        public int CardColorId { get; set; }
        public int ResidenceDegreeId { get; set; }
        public int MedicalNetworkId { get; set; }
        public int MainId { get; set; }
        public string ClassCode { get; set; }
        public decimal Accidents { get; set; }
        public decimal Death { get; set; }   
    }
}
