//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMS_Authontication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequestAddProvider
    {
        public long ID { get; set; }
        public string CompName { get; set; }
        public string ServName { get; set; }
        public string ServAddress { get; set; }
        public string PhoneNumber { get; set; }
        public int NumberOfPeople { get; set; }
        public Nullable<int> ProviderType { get; set; }
        public string Country { get; set; }
        public string Region { get; set; }
        public string ResponsableFor { get; set; }
        public string RespobeStatus { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<bool> IsSync { get; set; }
        public Nullable<System.DateTime> SyncDate { get; set; }
        public string SyncBy { get; set; }
        public string Status { get; set; }
        public string ReasonRefuse { get; set; }
    
        public virtual ProviderTypeNew ProviderTypeNew { get; set; }
    }
}
