//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMS_Authontication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReviewClaim
    {
        public long Id { get; set; }
        public Nullable<long> ClaimNo { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ClaimDate { get; set; }
        public string CardNo { get; set; }
        public Nullable<int> CompId { get; set; }
        public string ClassCode { get; set; }
        public Nullable<int> EmpCode { get; set; }
        public string EmpAname { get; set; }
        public string EmpEname { get; set; }
        public string Takhasos { get; set; }
        public Nullable<int> PrvNo { get; set; }
        public string PrvName { get; set; }
        public string ProviderType { get; set; }
        public string ServType { get; set; }
        public string Services { get; set; }
        public string ServName { get; set; }
        public Nullable<double> ClaimSubmitted { get; set; }
        public Nullable<double> OverInsurance { get; set; }
        public Nullable<double> Discount { get; set; }
        public Nullable<double> ApprovAmount { get; set; }
        public Nullable<double> CopayAmt { get; set; }
        public Nullable<double> AfterCopay { get; set; }
        public Nullable<double> LocalAmount { get; set; }
        public Nullable<double> ImportAmount { get; set; }
        public Nullable<double> LocalDisc { get; set; }
        public Nullable<double> ImportDisc { get; set; }
        public Nullable<double> TotalDiscount { get; set; }
        public Nullable<double> Net { get; set; }
        public string Notes { get; set; }
        public Nullable<int> BatchNo { get; set; }
        public Nullable<long> InvoiceNo { get; set; }
        public string UploadBy { get; set; }
        public Nullable<System.DateTime> UploadDate { get; set; }
        public Nullable<int> MainCompId { get; set; }
        public string MainCompName { get; set; }
    }
}
