//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMS_Authontication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReviewClaimsNew
    {
        public long Id { get; set; }
        public Nullable<long> CompId { get; set; }
        public string CompName { get; set; }
        public Nullable<System.DateTime> DoneDate { get; set; }
        public Nullable<int> BatchNo { get; set; }
        public Nullable<int> EmpCode { get; set; }
        public string CardNo { get; set; }
        public string EmpName { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public string ServName { get; set; }
        public Nullable<double> Gross { get; set; }
        public Nullable<double> CopayAmt { get; set; }
        public Nullable<double> Discount { get; set; }
        public Nullable<double> Net { get; set; }
        public Nullable<System.DateTime> ClaimDate { get; set; }
        public string ServCode { get; set; }
        public Nullable<int> PrvNo { get; set; }
        public string PrvName { get; set; }
        public Nullable<int> TypeEmp { get; set; }
        public Nullable<long> TaxCard { get; set; }
        public Nullable<long> TaxFile { get; set; }
        public Nullable<int> MissionCode { get; set; }
        public Nullable<long> ClaimNo { get; set; }
        public Nullable<int> MainCompId { get; set; }
        public string MainCompName { get; set; }
        public string UploadBy { get; set; }
        public Nullable<System.DateTime> UploadDate { get; set; }
    }
}
