//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMS_Authontication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoshitaDetail
    {
        public long Id { get; set; }
        public string MedicienCode { get; set; }
        public string MedicienName { get; set; }
        public int Dose { get; set; }
        public int Duration { get; set; }
        public int TotalDuration { get; set; }
        public Nullable<int> TotalUnits { get; set; }
        public double Amount { get; set; }
        public Nullable<bool> IsDealed { get; set; }
        public long RoshitaID { get; set; }
        public string PaymentGroup { get; set; }
        public Nullable<bool> IsSync { get; set; }
        public Nullable<System.DateTime> SyncDate { get; set; }
        public string SyncBy { get; set; }
        public string MedicineNoPay { get; set; }
    
        public virtual Roshita Roshita { get; set; }
    }
}
