//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMS_Authontication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Roshita
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Roshita()
        {
            this.RoshitaDetails = new HashSet<RoshitaDetail>();
            this.RoshitaPharmcyApproveds = new HashSet<RoshitaPharmcyApproved>();
            this.RoshitaDiagnosisAdmins = new HashSet<RoshitaDiagnosisAdmin>();
            this.PrescriptionRoshitaDignosis = new HashSet<PrescriptionRoshitaDignosi>();
            this.Notifications = new HashSet<Notification>();
        }
    
        public long Id { get; set; }
        public Nullable<long> Oracle_Id { get; set; }
        public string CardId { get; set; }
        public string Speciality { get; set; }
        public string Diagnose1 { get; set; }
        public string Diagnose2 { get; set; }
        public string diagnose3 { get; set; }
        public string RoshetaType { get; set; }
        public int Limit { get; set; }
        public int CompanyPercent { get; set; }
        public Nullable<double> OverInsurance { get; set; }
        public Nullable<double> TotalValue { get; set; }
        public double CompanyPayment { get; set; }
        public double PersonPayment { get; set; }
        public Nullable<double> Cash { get; set; }
        public string Manager { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<int> PatchId { get; set; }
        public string PhoneNumber { get; set; }
        public Nullable<double> ClaimNumber { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<bool> IsSync { get; set; }
        public Nullable<System.DateTime> SyncDate { get; set; }
        public string SyncBy { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string IsFamily { get; set; }
        public string IsPool { get; set; }
        public Nullable<long> Oracle_Id_Top { get; set; }
    
        public virtual Patch Patch { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RoshitaDetail> RoshitaDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RoshitaPharmcyApproved> RoshitaPharmcyApproveds { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RoshitaDiagnosisAdmin> RoshitaDiagnosisAdmins { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PrescriptionRoshitaDignosi> PrescriptionRoshitaDignosis { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Notification> Notifications { get; set; }
    }
}
