//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMS_Authontication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoshitaAcception
    {
        public int Id { get; set; }
        public long RoshitaId { get; set; }
        public int AcceptionId { get; set; }
    }
}
