//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMS_Authontication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ser_Prov_Disc
    {
        public int Id { get; set; }
        public int PROV_ID { get; set; }
        public string PROV_NAME { get; set; }
        public int LOC_DIS { get; set; }
        public int DEV_LOC_DIS { get; set; }
        public int IMP_DIS { get; set; }
        public int DEV_IMP_DIS { get; set; }
        public int PRV_TYPE { get; set; }
        public string TERMINATE_FLAG { get; set; }
        public Nullable<System.DateTime> TERMINATE_DATE { get; set; }
        public string USER_CR { get; set; }
        public Nullable<System.DateTime> USER_DT { get; set; }
        public string USER_UP { get; set; }
        public Nullable<System.DateTime> USER_DT_UP { get; set; }
        public string MOBIL { get; set; }
        public string MOBIL2 { get; set; }
        public string PHON { get; set; }
        public string PHON2 { get; set; }
        public string MAIL { get; set; }
        public string MAIL2 { get; set; }
        public string AD_STREET { get; set; }
        public string AD_ARYA { get; set; }
        public Nullable<int> FREE_LIM { get; set; }
        public Nullable<bool> IsSync { get; set; }
        public Nullable<System.DateTime> SyncDate { get; set; }
        public string SyncBy { get; set; }
    }
}
