//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMS_Authontication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Serv_Lab
    {
        public long Id { get; set; }
        public long LAB_CODE { get; set; }
        public long PR_CODE { get; set; }
        public string PR_ANAME { get; set; }
        public long DMS_CODE { get; set; }
        public long SERV_CODE { get; set; }
        public double SERV_AMOUNT { get; set; }
        public string SERV_ANAME { get; set; }
        public string GRUOP_TYPE { get; set; }
        public short LOOK { get; set; }
        public long GRUOP_ID { get; set; }
        public string GRUOP_NAME { get; set; }
        public Nullable<bool> IsSync { get; set; }
        public Nullable<System.DateTime> SyncDate { get; set; }
        public string SyncBy { get; set; }
    }
}
