//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMS_Authontication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SERV_PROVIDERS_NEW
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SERV_PROVIDERS_NEW()
        {
            this.ProviderComplaints = new HashSet<ProviderComplaint>();
            this.DeliveryRequests = new HashSet<DeliveryRequest>();
        }
    
        public long Id { get; set; }
        public Nullable<int> PR_CODE { get; set; }
        public Nullable<int> COMP_ID { get; set; }
        public Nullable<int> BRANCH_CODE { get; set; }
        public Nullable<int> PRV_TYPE { get; set; }
        public string PR_ANAME { get; set; }
        public string PR_ENAME { get; set; }
        public Nullable<int> OLD_PR_CODE { get; set; }
        public string DOC_SPEC { get; set; }
        public string PR_DESC { get; set; }
        public string ADDRESS1 { get; set; }
        public string ADDRESS2 { get; set; }
        public string TEL1 { get; set; }
        public string TEL2 { get; set; }
        public string FAX { get; set; }
        public string EMAIL { get; set; }
        public Nullable<int> AREA_CODE { get; set; }
        public string PERSON1 { get; set; }
        public string PERSON2 { get; set; }
        public string PERSON1_TEL { get; set; }
        public string PERSON2_TEL { get; set; }
        public string INSIDE_NWT { get; set; }
        public string OUTSIDE_NWT { get; set; }
        public string TERMINATE_FLAG { get; set; }
        public Nullable<System.DateTime> CONTRACT_DATE { get; set; }
        public Nullable<System.DateTime> TERMINATE_DATE { get; set; }
        public Nullable<int> PR_TYPE { get; set; }
        public Nullable<int> PR_AREA_COVER { get; set; }
        public Nullable<System.DateTime> TAX_AVOID_DATE { get; set; }
        public string TAX_CARD { get; set; }
        public string TAX_FILE { get; set; }
        public Nullable<int> PAY_PER_MONTH { get; set; }
        public Nullable<int> TAX_FLG { get; set; }
        public Nullable<int> SERV_FLG { get; set; }
        public Nullable<int> STAMP_VALUE { get; set; }
        public string TAX_ROOM { get; set; }
        public Nullable<int> SUB_PRV_TYPE { get; set; }
        public Nullable<int> ISSUE_PER_YEAR { get; set; }
        public Nullable<int> PR_TAX1 { get; set; }
        public Nullable<int> PR_TAX2 { get; set; }
        public string PROV_DEGREE { get; set; }
        public Nullable<int> DEV_CHK { get; set; }
        public Nullable<int> P_LIST { get; set; }
        public Nullable<int> PRICE_DISC { get; set; }
        public Nullable<int> REORDER_LEVEL { get; set; }
        public string ACTIVE { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
        public string UPDATE_BY { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public string GL_ACC_NO { get; set; }
        public string ACC_NO_DED_TAX { get; set; }
        public Nullable<int> MAX_APPROVAL_NO { get; set; }
        public Nullable<int> MAX_APPROVAL_AMT { get; set; }
        public Nullable<int> FOR_MED_DIS { get; set; }
        public Nullable<int> LOCAL_MED_DIS { get; set; }
        public string MAIN_SERV { get; set; }
        public Nullable<int> DEV_STAND { get; set; }
        public Nullable<int> DEV_LOC { get; set; }
        public Nullable<int> DEV_EXT { get; set; }
        public Nullable<int> GOVERNMENT_CODE { get; set; }
        public string ACTIVATION_BY { get; set; }
        public Nullable<System.DateTime> ACTIVATION_DATE { get; set; }
        public string DEACTIVATION_BY { get; set; }
        public Nullable<System.DateTime> DEACTIVATION_DATE { get; set; }
        public string REASON_DEACTIVATION { get; set; }
        public string REASON_ACTIVATION { get; set; }
        public string MAIN_CODE { get; set; }
        public Nullable<bool> IsSync { get; set; }
        public string SyncBy { get; set; }
        public Nullable<System.DateTime> SyncDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProviderComplaint> ProviderComplaints { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DeliveryRequest> DeliveryRequests { get; set; }
    }
}
