//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMS_Authontication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsersInternalCode
    {
        public int Id { get; set; }
        public string CardId { get; set; }
        public string EnglishName { get; set; }
        public string NickName { get; set; }
        public string InternalCode { get; set; }
        public string MobileNumber { get; set; }
        public string Email { get; set; }
    }
}
