// <auto-generated />
namespace DMS_Authontication1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Modification2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Modification2));
        
        string IMigrationMetadata.Id
        {
            get { return "201811271146400_Modification2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
